repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.4
  hooks:
    - id: ruff
      entry: poetry run ruff
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.931
  hooks:
    - id: mypy
      args: ["--install-types", "--non-interactive", "--ignore-missing-imports"]
